# suppress inspection "UnusedProperty" for whole file
spring.application.name=chronos
logging.level.root=INFO
smart.qc.enable.raft=true

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.producer.bootstrap-servers=localhost:9092
